
AA_LOC_NODE = "SideOPFOR_F";
AA_LOC_DETC = "EmptyDetector";

#include "x\ambientarma\aa_graph\get_node.sqf"
#include "x\ambientarma\aa_graph\export_graph.sqf"
#include "x\ambientarma\aa_graph\import_graph.sqf"
#include "x\ambientarma\aa_graph\create_node.sqf"
#include "x\ambientarma\aa_graph\link_nodes.sqf"
#include "x\ambientarma\aa_graph\node_get_trigger.sqf"
#include "x\ambientarma\aa_graph\node_get_children.sqf"
#include "x\ambientarma\aa_graph\node_get_houses.sqf"
#include "x\ambientarma\aa_graph\node_get_roads.sqf"
#include "x\ambientarma\aa_graph\node_get_units.sqf"
#include "x\ambientarma\aa_graph\node_get_exit_roads.sqf"
#include "x\ambientarma\aa_graph\node_side_count.sqf"
#include "x\ambientarma\aa_graph\node_side_units.sqf"
#include "x\ambientarma\aa_graph\node_side_present.sqf"
#include "x\ambientarma\aa_graph\node_get_groups.sqf"
#include "x\ambientarma\aa_graph\node_debug_print.sqf"
#include "x\ambientarma\aa_graph\node_best_places.sqf"
#include "x\ambientarma\aa_graph\node_get_indoor_houses.sqf"
#include "x\ambientarma\aa_graph\find_path.sqf"
#include "x\ambientarma\aa_graph\find_path_efficient.sqf"
#include "x\ambientarma\aa_graph\find_path_inefficient.sqf"
#include "x\ambientarma\aa_graph\node_get_children_asc.sqf"
#include "x\ambientarma\aa_graph\node_get_children_desc.sqf"
#include "x\ambientarma\aa_graph\find_nearest_node.sqf"
#include "x\ambientarma\aa_graph\nodes_connected.sqf"
#include "x\ambientarma\aa_graph\node_is_safe.sqf"
#include "x\ambientarma\aa_graph\node_side_groups.sqf"
#include "x\ambientarma\aa_graph\list_nodes.sqf"
#include "x\ambientarma\aa_graph\debug_nodes.sqf"
#include "x\ambientarma\aa_graph\draw_graph.sqf"
#include "x\ambientarma\aa_graph\node_get_type.sqf"
#include "x\ambientarma\aa_graph\node_get_random_houses.sqf"
