
AA_LOC_NODE = "location_aanode";
AA_LOC_DETC = "EmptyDetector";

#include "get_node.sqf"
#include "export_graph.sqf"
#include "import_graph.sqf"
#include "create_node.sqf"
#include "link_nodes.sqf"
#include "node_get_trigger.sqf"
#include "node_get_children.sqf"
#include "node_get_houses.sqf"
#include "node_get_roads.sqf"
#include "node_get_units.sqf"
#include "node_get_exit_roads.sqf"
#include "node_side_count.sqf"
#include "node_side_units.sqf"
#include "node_side_present.sqf"
#include "node_get_groups.sqf"
#include "node_debug_print.sqf"
#include "node_best_places.sqf"
#include "node_get_indoor_houses.sqf"
#include "find_path.sqf"
#include "find_path_efficient.sqf"
#include "find_path_inefficient.sqf"
#include "node_get_children_asc.sqf"
#include "node_get_children_desc.sqf"
#include "find_nearest_node.sqf"
#include "nodes_connected.sqf"
#include "node_is_safe.sqf"
#include "node_side_groups.sqf"
#include "list_nodes.sqf"
#include "debug_nodes.sqf"
#include "draw_graph.sqf"
#include "node_get_type.sqf"
#include "node_get_random_houses.sqf"
